import { stationList } from "src/components/sections/stationBox/types";

export const stationBox: stationList = [
  {
    id: "sirup-2",
    title: "FULLTIME: JUNIOR FRONTEND DEVELOPER ",
    institution: "SIRUP GmbH",
    duration: "since 03/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: [
      "React, Drupal, Symfony and vanilla implementations",
      "Creation and enhancement of bundling, linting and testing",
      "Creation of reusable componentsystems, templates & packages",
    ],
  },
  {
    id: "sirup-1",
    title: "WORKING STUDENT: FRONTEND DEVELOPMENT ",
    institution: "SIRUP GmbH",
    duration: "02/2021 - 02/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: [
      "React, Drupal, Symfony and vanilla implementations",
      "Creation and enhancement of bundling, linting and testing",
      "Newsletter template development",
    ],
  },
  {
    id: "hdm-1",
    title: "BACHELOR OF ARTS: ONLINE-MEDIEN-MANAGEMENT",
    institution: "Stuttgart Media University",
    duration: "2017 - 2022",
    location: "Stuttgart",
    icon: "hdm",
    link: "https://www.omm.hdm-stuttgart.de/",
    linkTitle: "Online media management website",
    infos: [
      "Final grade: 1,6",
      "Thesis: Prototypical development of a WYSIWYG end-user editor for web pages according to atomic design principles with React within a JAMstack architecture.",
      "IT basics, programming & webdevelopment",
      "Digital marketing & data analytics",
      "Digital content creation",
    ],
  },
  {
    id: "inpulse",
    icon: "readyfortechno",
    title: "FREELANCE: EVENT-MANAGEMENT AGENCY",
    institution: "inPulse | Klummer und Tondera GbR",
    duration: "2018 - 2022",
    location: "Heilbronn",
    infos: [
      "Digital content creation including graphic design and development",
      "Branding & performance marketing",
      "Event- and projectmanagement",
    ],
  },
  {
    id: "vinos",
    icon: "vinos",
    title: "INTERNSHIP: E-COMMERCE CRM MARKETING",
    institution: "Wein & Vinos GmbH",
    duration: "09/2019 - 02/2020",
    location: "Berlin",
    link: "https://www.vinos.de/",
    linkTitle: "Wein & Vinos online shop",
    infos: [
      "E-mail marketing, templating & analytics",
      "Landingpage creation and productdata-management with Magento",
      "Customer relationship management",
    ],
  },
];
