import Head from "next/head";
import { Hero } from "src/components/organisms/hero/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Julian Klummer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
      </div>
    </>
  );
}
