import { stationList } from "./types";

export const stationBox: stationList = [
  {
    id: "sirup-2",
    title: "FULLTIME: JUNIOR FRONTEND DEVELOPER ",
    institution: "SIRUP GmbH",
    duration: "since 03/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: ["Frontend Development"],
  },
  {
    id: "sirup-1",
    title: "WORKING STUDENT: FRONTEND DEVELOPMENT ",
    institution: "SIRUP GmbH",
    duration: "02/2021 - 02/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: ["Frontend Development"],
  },
  {
    id: "hdm-1",
    title: "BACHELOR OF ARTS: ONLINE-MEDIEN-MANAGEMENT",
    institution: "Stuttgart Media University",
    duration: "2017 - 2022",
    location: "Stuttgart",
    icon: "hdm",
    link: "https://www.omm.hdm-stuttgart.de/",
    linkTitle: "Online media management website",
    infos: [
      "Online technologies, webdesign & programming",
      "Digital marketing & data analytics",
      "Digital content creation",
    ],
  },
  {
    id: "inpulse",
    icon: "inpulse",
    title: "FREELANCE: EVENT-MANAGEMENT AGENCY",
    institution: "inPulse | Klummer und Tondera GbR",
    duration: "2018 - 2022",
    location: "Heilbronn",
    infos: ["Event- und brandmanagement", "Online & offline marketing"],
  },
  {
    id: "vinos",
    icon: "vinos",
    title: "INTERNSHIP: E-COMMERCE CRM MARKETING",
    institution: "Wein & Vinos GmbH",
    duration: "09/2019 - 02/2020",
    location: "Berlin",
    link: "https://www.vinos.de/",
    linkTitle: "Wein & Vinos online shop",
    infos: [
      "Customer relationship management",
      "E-Mail Marketing & analytics",
      "E-Commerce",
    ],
  },
];
