import { stationList } from "src/components/sections/stationBox/types";

export const stationBox: stationList = [
  {
    id: "sirup-2",
    title: "VOLLZEIT: JUNIOR FRONTEND DEVELOPER ",
    institution: "SIRUP GmbH",
    duration: "seit 03/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: [
      "React, Drupal, Symfony und Vanilla Implementierungen",
      "Erstellung und Verbesserung von Bundling, Linting und Testing",
      "Erstellung von wiederverwendbaren Komponentensystemen, Templates & Packages",
    ],
  },
  {
    id: "sirup-1",
    title: "WERKSSTUDENT: FRONTEND DEVELOPMENT ",
    institution: "SIRUP GmbH",
    duration: "02/2021 - 02/2022",
    location: "Berlin",
    icon: "sirup",
    link: "https://www.sirup.com/",
    linkTitle: "SIRUP Website",
    infos: [
      "React, Drupal, Symfony und Vanilla Implementierungen",
      "Erstellung und Verbesserung von Bundling, Linting und Testing",
      "Entwicklung von Newsletter Templates",
    ],
  },
  {
    id: "hdm-1",
    title: "BACHELOR OF ARTS: ONLINE-MEDIEN-MANAGEMENT",
    institution: "Hochschule der Medien Stuttgart",
    duration: "2017 - 2022",
    location: "Stuttgart",
    icon: "hdm",
    link: "https://www.omm.hdm-stuttgart.de/",
    linkTitle: "Online Medien Management Studiengangs Website",
    infos: [
      "Abschlussnote: 1,6",
      "Abschlussarbeit: Prototypische Entwicklung eines WYSIWYG End-User Editors für Webpages nach Atomic Design Prinzipien mit React innerhalb einer JAMstack Architektur",
      "IT-Grundlagen, Programmierung & Webentwicklung",
      "Digitales Marketing & Datenanalyse",
      "Digitale Inhalteerstellung",
    ],
  },
  {
    id: "inpulse",
    title: "SELBSTÄNDIG: EVENT-MANAGEMENT AGENTUR",
    institution: "inPulse | Klummer und Tondera GbR",
    duration: "2018 - 2022",
    location: "Heilbronn",
    icon: "readyfortechno",
    infos: [
      "Erstellung von digitalen Inhalten inklusive Grafikdesign und Entwicklung",
      "Branding & Performancemarketing",
      "Event- und Projektmanagement",
    ],
  },
  {
    id: "vinos",
    title: "PRAKTIKUM: E-COMMERCE CRM MARKETING",
    institution: "Wein & Vinos GmbH",
    duration: "09/2019 - 02/2020",
    location: "Berlin",
    icon: "vinos",
    link: "https://www.vinos.de/",
    linkTitle: "Wein & Vinos Online Shop",
    infos: [
      "E-Mail-Marketing, Templating und Analytics",
      "Erstellung von Landingpages und Produktdatenmanagement mit Magento",
      "Customer relationship management",
    ],
  },
];
